### ISSUE TITLE
Just Nothing Shows Up

### ISSUE THREAD

**Issue by Indy27** [Kcchouette/XDCC-simple#10]
Did everything in the installation.
Moved the folder into my blog's directory.
Inputted what was needed (the bot's name, url of packlist, url of irc) 
XML was confusing, like, what am I supposed to put down here? From the FTP directory or from whatever site that hosts XML files?
So after all of that, it says the bots were added successfully but they don't show up at all...

**Comment by Kcchouette** [comment]
Hello, thank you for your interest in this project.

You should only modify ONE file manually, the file config.php

Can you see the index.php of XDCC-simple? Can you take screenshot of it?
There should be a home button

What if you try to access to `<url_of_XDCC-simple>/admin.php`?

**Comment by Indy27** [comment]
Yeah I can modify the admin/pass and irc from there right. Can access admin.php fine, too.

Screenshots:

![error2](https://user-images.githubusercontent.com/16329147/63193358-4719fe00-c03b-11e9-9d16-3e599e3f1af0.png)
![error3](https://user-images.githubusercontent.com/16329147/63193359-4719fe00-c03b-11e9-9cfd-9d8df224d3a1.png)
![error1](https://user-images.githubusercontent.com/16329147/63193357-4719fe00-c03b-11e9-94e6-817bc48725c3.png)

**Comment by Indy27** [comment]
XML I had to upload to a filehost, only gave me the link instead of (url)/(name).xml. Tried inserting the ftp method of the xml. No avail to both.

**Comment by Kcchouette** [comment]
Thank you.

"XML of the bot" is the file generated by iroffer. You should firstly having it created by modifying the iroffer config file (by removing `#` [here](https://github.com/dinoex/iroffer-dinoex/blob/9cb3f8c3c4c6112068a4ac741cb32b6a0340280d/sample.config#L108) and should be on same host than the bot

**Comment by Kcchouette** [comment]
Remote XML file is currently not supported, see #8 
You should instead put the path to the file (eg /home/folder/iroffer.xml)

**Comment by Indy27** [comment]
Yeah all my bots have the # removed after xdccxmlfile.  

So the thing only works in the / directory (and here I am thinking /www/(site)/(name).xml would work

**Comment by Kcchouette** [comment]
Hopping it'll work :smile: 

And yes, it only work in the / directory, so XDCC-simple and the XML should be on the **same** host

**Comment by Indy27** [comment]
Aaaaand nope.

Even moving the xml files in the same place as xdcc-simple and even inside xdcc-simple wouldn't work.  I would need a clear screenshot of a better example of how it should be done.  Seems the only thing that will work is moving xdcc-simple to my site's directory and doing everything right **but** getting the bots to show.  

I really want to try this thing out because, there aren't any other xdcc parsers out there, and the more advanced global one is a pain in the ass just _**trying**_ to install it.

**Comment by Kcchouette** [comment]
For example, inside `xdcc-simple`, you need to write something like `./file.xml`.
Or in the same place, `../file.xml`.

**Comment by Kcchouette** [comment]
A real example: inside my folder xdcc-simple, I have theses files
```
$ ls
admin_action.php  config.php    img        login.php   syndication.php
admin.php         css           index.php  logout.php  TODO.md
cache             database.php  json       mybot.xml   update.php
class             extra         LICENSE    README.md   xdcc.php
```
We can see `mybot.xml` that is an iroffer XML file.

So I'm putting this:

![Screenshot_2019-08-16 XDCC - Admin Page](https://user-images.githubusercontent.com/3000936/63197568-73a03b00-c078-11e9-80c7-3cfbb89f3529.png)

And it works

**Comment by Kcchouette** [comment]
If I open "mybot.xml", you should see a file something like that:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iroffer PUBLIC "-//iroffer.dinoex.net//DTD iroffer 1.0//EN" "http://iroffer.dinoex.net/dtd/iroffer-10.dtd">
<iroffer>
<packlist>

<pack>
  <packnr>1</packnr>
```

**Comment by Indy27** [comment]
Basically what my ftp looks like 

![ftp](https://user-images.githubusercontent.com/16329147/63197930-25bf0f00-c047-11e9-875f-fbedb03df356.png)
The three xml files inside are all bots. Since I'm sure these three are in the same place, I'm assuming all of them would be ../name of file.xml?

**Comment by Kcchouette** [comment]
No, all should be `./name of the file.xml` in this case

**Comment by Kcchouette** [comment]
If it's not working, can you check that the bot JSON file is updated?
After saving the "add a bot" page, just open `json/data.json` and check that the content is updated by that you've put in the php page (be careful, `./nameofthebot.xml` will become `.\/nameofthebot.xml`

**Comment by Indy27** [comment]
Opened up data.json and only the test bot is there.

**Comment by Kcchouette** [comment]
mmh, should be a problem with linux permission :(

Can you put good permission at the `json` folder so that your www process can modify the file? For example `chmod -R a+rw json` ?

**Comment by Kcchouette** [comment]
Else, as a temporary fix, you can edit the `json/data.json` file manually but it's not a long-term fix that I recommend.

**Comment by Indy27** [comment]
Well, I tried the manual one hours ago and that not only would've opened up it killed the test bot as well. 

Change json folder to chmod 777 (I dunno the one you put down)?

**Comment by Kcchouette** [comment]
>  I tried the manual one hours ago and that not only would've opened up it killed the test bot as well

To be honest, in my case, it's a daily replication of XML file that is used by xdcc-simple, not the "real" file generated by iroffer, but a copy. Maybe this is a new bug too :(

**Comment by Kcchouette** [comment]
> Change json folder to chmod 777 (I dunno the one you put down)?

let's try, hoping it'll work :pray:

**Comment by Indy27** [comment]
The only thing I can see why it ain't working is maybe the site where the bot is linked, but those sites are packlist sites, so it can't be that.  

I also realized something, 

> XML File from Iroffer (remove the # from #xdccxmlfile mybot.xml)

That's in the config file, though. Would it be possible that the bot's conf files should also be in the same directory with the xml/xdcc-simple (since the conf and xml files are in two different ftp accounts, well, the xml files are also where the conf files are at, too)?

**Comment by Kcchouette** [comment]
>  those sites are packlist sites

Maybe all packlists try to access of the file?

> Would it be possible that the bot's conf files should also be in the same directory with the xml/xdcc-simple (since the conf and xml files are in two different ftp accounts, well, the xml files are also where the conf files are at, too)?

No.
In my case, `/home/user/iroffer/` has all for iroffer. It generate the xml file, that is copy to another host `/www/xdcc-simple/`.
xdcc-simple does nothing with the conf, it only try to open the xml and display it if he can

**Comment by Indy27** [comment]
Yeah, that makes sense.

I (am going to assume here) that one ftp account that I have, which isn't mine but does have my bots hosted, contains the xmls, logs, confs, and the **state** files, something my real account doesn't have but hosts the xdcc files of those bots, my website, etc. What if the xmls that I copypasta from one ftp to the ftp with xdcc-simple wasn't working because the .state files weren't in the same account?

**Comment by Kcchouette** [comment]
Like I said, **this php projet _only_ use the XML**, it does matter of other files of iroffer (the state, log, conf, etc).

**Comment by Kcchouette** [comment]
@Indy27 My last commit https://github.com/Kcchouette/XDCC-simple/commit/08df83788edd1ca156f874a44ffd0f84e8086ea2 uses a function that show files-reading error in the php log file. It can help. Moreover, it now supports remote URL.

(eg: `PHP Warning:  file_get_contents(./mybot.xml): failed to open stream: Permission denied in xdcc.php on line 11`, or `file_get_contents(../mybot.xml): failed to open stream: No such file or directory in xdcc.php on line 11`)

**Comment by Indy27** [comment]
Sorry, my internet somewhat died for 2 hours and had to re-start my PC.

**Comment by Indy27** [comment]
Okay. I can't believe this actually worked...FINALLY! Instead of ../(insert xml here) I just named a new folder, moved the bots there, did (folder)/(bot).xml, didn't do the url link, and VOILA!  Man, I don't know how many hours I've spend on getting this to work!

**Comment by Indy27** [comment]
ever think of adding more .css in the near future?

**Comment by Kcchouette** [comment]
I'm happy that you succeed in some way.

If one day you try to reproduce the issue, do not hesitate to comment here, and try to see if no error appears in the log of PHP ( /var/log/php_errors.log by default). It can improve the stability of this software :)

About more CSS, I'm not a fan of coding CSS. But I accept Pull Request :smile:
