### ISSUE TITLE
xdcc fetcher

### ISSUE THREAD

**Issue by ikuria** [Kcchouette/XDCC-simple#13]
hi, i'm using your xdcc fetcher, but the downloaded files are corrupt, did you know why this happens? maybe you can help to find the problem?! pls conact me

**Comment by Kcchouette** [comment]
Tbh I don't remember what I was doing at this moment, but I've a second branch on this project named `Kcchouette-renew` that can be most up to date?
I've found some issues like https://github.com/Kcchouette/XDCC-fetcher/issues/4 but as I'm not using it anymore, I can only letting your improving it on your side.
