### ISSUE TITLE
Change CSS framework

### ISSUE THREAD

**Issue by Kcchouette** [Kcchouette/XDCC-simple#2]
I want
- Less than 15 kB (omgcss = 9,07 kB)
- with navbar and other option like OMGCSS
- Open Source

**Comment by Kcchouette** [comment]
- [ ] [Tacit](http://www.yegor256.com/2015/04/13/tacit-css-framework-for-dummies.html) - 4,42 KB
- [ ] [Papier](https://github.com/alexanderGugel/papier) - 10,6 KB

**Comment by Kcchouette** [comment]
- [ ] [Juiced](http://juicedcss.com/) - 61,03 kB
- [ ] [Furtive](http://furtive.co/) - 10,02 kB
- [ ] [Bulma](http://bulma.io/) - 90,72 kB
- [ ] [Blaze_CSS](http://blazecss.com/) - 62,04 kB
- [ ] [Cutestrap](https://www.cutestrap.com/) - 13,92 kB
- [ ] [ConciseCSS](http://concisecss.com/documentation/) - 14,6 kB
- [ ] [Spectre.css](https://picturepan2.github.io/spectre/)  - 40,95 kB
- [ ] [Milligram](https://milligram.github.io/) - 14,32 kB

**Comment by Kcchouette** [comment]
- [ ] [Pure.css](http://purecss.io/) - 16,88 kB + 9.57 kB for responsivity of grid

**Comment by Kcchouette** [comment]
- [siimple](https://github.com/siimple/siimple) - 5.64 kB
- [wing](https://github.com/kingpixil/wing) - 4.58 kB

**Comment by ghost** [comment]
wing seems nice, but no menu :(

**Comment by Kcchouette** [comment]
I've begin with wing. I don't really search a big menu build like you but a simple navbar.
