### ISSUE TITLE
remote xml files

### ISSUE THREAD

**Issue by Seeder101** [Kcchouette/XDCC-simple#8]
Hi Kcchouette
I really liked ur xdcc parser but I couldn't link a packlist from a remote server say
http://serverip/mybot.xml 
or does this xml work only locally ? I did move the xml file to the web site server and put it there and point it to the local path and it worked 

Thanks in advance

**Comment by Kcchouette** [comment]
Hello, thank you for your interest in this project.
You cannot link a packlist from a remote server for the moment. It was planned on a non-dated future version (https://github.com/Kcchouette/XDCC-simple/blob/master/TODO.md#for-v03 > Download the XML file (from URL)?)

So for the moment it only work with xml locally.

If you have skills to help me implementing this feature, do not hesitate to do a PR. For the moment, I'm focused to finish SpectreCSS integration and #7

**Comment by Kcchouette** [comment]
XDCC-simple now supports XML remote file.

Thanks for waiting, @Seeder101

**Comment by Seeder101** [comment]
> XDCC-simple now supports XML remote file.
> 
> Thanks for waiting, @Seeder101

Thank you. Much appreciated.
does that support FTP/HTTP these two are the main Protocols as they are used so often with Parser especially HTTP.

**Comment by Kcchouette** [comment]
@Seeder101 normally yes. I've tested ftp and http.
If you see some non-working protocols/url, do not hesitate to open another issue
